version: "3.9"
services:
  my_awesome_db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "127.0.0.1:25432:5432"
      - "5432:5432"
    container_name: postgresql-local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=sonar
    volumes:
      - "D:\\DockerData\\sonarqube\\postgres.sock:/var/run/postgres/postgres.sock"
      - "D:\\DockerData\\sonarqube\\postgres:/var/lib/postgresql/data"
    networks:
      db:
        aliases:
          - postgres
  sonarqube:
    image: sonarqube:8.9.0-community
    container_name: sonarqube
    depends_on:
        - my_awesome_db
    ports:
        - "9000:9000"
        - "127.0.0.1:2999:9000"
    environment:
        SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
        SONAR_JDBC_USERNAME: postgres
        SONAR_JDBC_PASSWORD: 123
        sonar.search.javaAdditionalOpts: -Dnode.store.allow_mmap=false
    volumes:
        - "D:\\DockerData\\sonarqube\\data:/opt/sonarqube/data"
        - "D:\\DockerData\\sonarqube\\extensions:/opt/sonarqube/extensions"
        - "D:\\DockerData\\sonarqube\\logs:/opt/sonarqube/logs"
        - "D:\\DockerData\\sonarqube\\temp:/opt/sonarqube/temp"
        - "D:\\DockerData\\sonarqube\\conf:/opt/sonarqube/conf"
    networks:
        - db
    shm_size: '2gb'
    ulimits:
        nofile:
            soft: "65535"
            hard: "65535"
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
        - "15432:80"
    environment:
        - GUNICORN_THREADS=1
        - PGADMIN_DEFAULT_EMAIL=vinicius.tonelli@gruponewway.com.br
        - PGADMIN_DEFAULT_PASSWORD=123
    volumes: 
        - "D:\\DockerData\\sonarqube\\pgadmin:/var/lib/pgadmin"
    networks:
        - db
    depends_on:
        - my_awesome_db
networks:
  db: